### ISSUE TITLE
Panic in the Triangle Demo

### ISSUE THREAD

**Issue by sandeep-datta** [vulkano-rs/vulkano-examples#31] opened 2018-08-27 18:39 UTC
Here is the stack trace...
```
#0  core::result::unwrap_failed (msg=..., error=vulkano::OutOfHostMemory) at /checkout/src/libcore/result.rs:983
#1  0x0000555555595bd7 in <core::result::Result<T, E>>::unwrap (self=...) at /checkout/src/libcore/result.rs:782
#2  0x00005555555bfbfa in vulkano::sync::future::fence_signal::then_signal_fence (future=..., behavior=...) at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.9.0/src/sync/future/fence_signal.rs:40
#3  0x00005555555e6fa3 in vulkano::sync::future::GpuFuture::then_signal_fence (self=...) at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.9.0/src/sync/future/mod.rs:217
#4  0x00005555555e6ff2 in vulkano::sync::future::GpuFuture::then_signal_fence_and_flush (self=...) at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.9.0/src/sync/future/mod.rs:227
#5  0x00005555555ff115 in triangle::main () at triangle/main.rs:440
```

H/W: Nvidia Graphics Card with proprietary driver version 396.26 on Kubuntu 18.04

**Comment by rukai** [comment] 2018-08-27 21:04
Duplicate of https://github.com/vulkano-rs/vulkano/issues/923
A workaround is here https://github.com/vulkano-rs/vulkano/pull/955

**Closed by rukai** 2018-08-27 21:04 UTC
