### ISSUE TITLE
Device lost on window resize

### ISSUE THREAD

**Issue by raphlinus** [vulkano-rs/vulkano-examples#18] opened 2017-12-08 19:09 UTC
I'm experimenting with the example, and finding that I get a DeviceLost when I resize the window

Using device: GeForce GTX 1060 (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeviceLost', src\libcore\result.rs:906:4

I could paste the backtrace but it's not that interesting, it's deep in a future chain from PresentFuture and CommandBufferExecFuture.

This only happens when I resize the window at normal speeds. If I resize super slowly, it works. Also if I tweak the example to use integrated graphics, it works. Also if I change it to use integrated graphics (Intel 630) it works.

Hardware: Gigabyte Aero 14
Driver Version	23.21.13.8859

**Comment by JohnDoneth** [comment] 2017-12-11 18:08
I receive the same Same `DeviceLost` `Err` on my GTX 970 and GTX 1050 on separate computers both running on Windows with the latest Nvidia Drivers when attempting to resize the window.

**Comment by main--** [comment] 2017-12-18 10:30
Windows seems to be the problem here. I'm hitting the same issue with Windows + Nvidia.

**Comment by JohnDoneth** [comment] 2017-12-18 18:50
@main-- I believe it's more specifically the Nvidia GPU Vulkan driver on Windows. Selecting an Integrated Intel HD GPU on the same computer works just fine. 

I wonder if the same problem occurs with Windows using AMD hardware and drivers. If not we can mark it as a driver bug?

**Comment by lbotsch** [comment] 2018-03-04 13:08
I get the exact same issue on Ubuntu using the Linux-x86_64 driver version 390.25 from Nvidia.

**Comment by azymohliad** [comment] 2018-03-12 11:41
Same thing on Archlinux, Geforce 940MX, Nvidia driver 390.25

**Comment by lbotsch** [comment] 2018-03-12 13:09
This is due to a bug that is fixed in the current vulkano master branch, see:

https://github.com/vulkano-rs/vulkano/commit/057507f7c2fd553ac7c80dff03c4a18f36f888f3

and

https://github.com/vulkano-rs/vulkano/commit/3231e92715e24ac466fae581e163c58a961cc51c

Please test the current master so this issue can be closed

**Comment by azymohliad** [comment] 2018-03-13 01:39
@lbotsch is it included in version 0.8 from crates.io or should I rebuild it from master locally? Btw, I didn't reproduce this issue with any example from main [vulkano](https://github.com/vulkano-rs/vulkano) repository.

**Comment by rukai** [comment] 2018-08-24 06:56
We still need to handle resize in the examples but that will be tracked in: https://github.com/vulkano-rs/vulkano-examples/issues/19

**Closed by rukai** 2018-08-24 06:56 UTC
